# Generated by Django 5.1.4 on 2024-12-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approved_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Nice', max_length=255)),
                ('organizers_name', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=255)),
                ('user_booked_date', models.DateTimeField(auto_now_add=True)),
                ('booked_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField()),
                ('no_of_people', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('status', models.CharField(default='APPROVED', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='every_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Nice', max_length=255)),
                ('organizers_name', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=255)),
                ('user_booked_date', models.DateTimeField(auto_now_add=True)),
                ('booked_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField()),
                ('no_of_people', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('status', models.CharField(default='PENDING', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='login_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_or_not', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_numbers', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='rejected_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Nice', max_length=255)),
                ('organizers_name', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=255)),
                ('user_booked_date', models.DateTimeField(auto_now_add=True)),
                ('booked_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField()),
                ('no_of_people', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('status', models.CharField(default='REJECTED', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
