# Generated by Django 5.1.4 on 2024-12-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parva_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved_events',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='every_events',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='login_info',
            name='phone_numbers',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rejected_events',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='venue',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
