# Generated by Django 5.1.4 on 2024-12-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parva_website', '0002_alter_approved_events_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved_events',
            name='event_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='every_events',
            name='event_name',
            field=models.CharField(max_length=255),
        ),
    ]
