# Generated by Django 5.1.4 on 2024-12-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parva_website', '0003_alter_approved_events_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venuePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
