# Generated by Django 5.1.4 on 2024-12-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parva_website', '0004_venue_venuephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved_events',
            name='venuePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='every_events',
            name='venuePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='rejected_events',
            name='venuePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
