# Generated by Django 5.1.4 on 2024-12-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parva_website', '0005_approved_events_venuephoto_every_events_venuephoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved_events',
            name='venuePhoto',
            field=models.CharField(default='nice', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='every_events',
            name='venuePhoto',
            field=models.CharField(default='nice', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rejected_events',
            name='venuePhoto',
            field=models.CharField(default='nice', max_length=255),
            preserve_default=False,
        ),
    ]
