# Generated by Django 5.1.4 on 2024-12-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parva_website', '0006_alter_approved_events_venuephoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved_events',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='approved_events',
            name='status',
            field=models.CharField(default='APPROVED', max_length=255),
        ),
        migrations.AlterField(
            model_name='approved_events',
            name='venue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='every_events',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='every_events',
            name='venue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='login_info',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='login_info',
            name='phone_numbers',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rejected_events',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rejected_events',
            name='status',
            field=models.CharField(default='REJECTED', max_length=255),
        ),
        migrations.AlterField(
            model_name='rejected_events',
            name='venue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
